apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platformServiceAccounts.fullname" . }}
  labels: {{ include "platformServiceAccounts.labels.standard" . | nindent 4 }}
    service: platform-service-accounts
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "platformServiceAccounts.name" . }}
      release: {{ .Release.Name }}
      service: platform-service-accounts
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "platformServiceAccounts.name" . }}
        release: {{ .Release.Name }}
        service: platform-service-accounts
    spec:
      containers:
      - name: platform-service-accounts
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        {{- if .Values.command }}
        command: {{ toYaml .Values.command | nindent 8 }}
        {{- end }}
        {{- if .Values.args }}
        args: {{ toYaml .Values.args | nindent 8 }}
        {{- end }}

        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /api/v1/ping
            port: tcp-web
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/v1/ping
            port: tcp-web
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
          - containerPort: {{ .Values.port }}
            name: tcp-web
            protocol: TCP
        {{- if .Values.resources }}
        resources: {{ toYaml .Values.resources | nindent 10 }}
        {{- end }}

        env:
        - name: NP_SERVICE_ACCOUNTS_API_PORT
          value: {{ .Values.port | quote }}
        - name: NP_SERVICE_ACCOUNTS_API_BASE_URL
          value: {{ .Values.platform.apiPublicUrl }}
        - name: NP_SERVICE_ACCOUNTS_API_PLATFORM_AUTH_URL
          value: {{ .Values.platform.authUrl }}
        - name: NP_SERVICE_ACCOUNTS_API_PLATFORM_AUTH_TOKEN

{{- if .Values.platform.token }}
{{ toYaml .Values.platform.token | indent 10 }}
{{- end }}

        {{- if .Values.cors.origins }}
        - name: NP_CORS_ORIGINS
          value: {{ .Values.cors.origins | join "," | quote }}
        {{- end }}
        {{- if .Values.zipkin }}
        - name: NP_ZIPKIN_URL
          value: {{ .Values.zipkin.url }}
        - name: NP_ZIPKIN_SAMPLE_RATE
          value: {{ .Values.zipkin.sampleRate | default 0 | quote }}
        {{- end }}
        {{- if .Values.sentry }}
        - name: NP_SENTRY_DSN
          value: {{ .Values.sentry.dsn }}
        - name: NP_SENTRY_CLUSTER_NAME
          value: {{ .Values.sentry.clusterName }}
        - name: NP_SENTRY_SAMPLE_RATE
          value: {{ .Values.sentry.sampleRate | default 0 | quote }}
        {{- end }}
        {{- if .Values.enableDocs }}
        - name: NP_SERVICE_ACCOUNTS_API_ENABLE_DOCS
          value: "true"
        {{- end }}
{{- if .Values.postgres.dsn }}
        - name: NP_DB_POSTGRES_DSN
{{ toYaml .Values.postgres.dsn | indent 10 }}
{{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
