apiVersion: v1
kind: Service
metadata:
  name: {{ include "platformServiceAccounts.fullname" . }}
  labels: {{ include "platformServiceAccounts.labels.standard" . | nindent 4 }}
    service: platform-service-accounts
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: NEURO_SERVICE_ACCOUNTS_API_SESSION
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: tcp-web
  selector:
    app: {{ include "platformServiceAccounts.name" . }}
    release: {{ .Release.Name }}
    service: platform-service-accounts
---
# TODO: Old service definition. Check that it is not used elsewhere and remove.
apiVersion: v1
kind: Service
metadata:
  name: platformserviceaccountsapi
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: NEURO_SERVICE_ACCOUNTS_API_SESSION
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: tcp-web
  selector:
    app: {{ include "platformServiceAccounts.name" . }}
    release: {{ .Release.Name }}
    service: platform-service-accounts
