apiVersion: v1
kind: Service
metadata:
  name: {{ include "platformServiceAccounts.fullname" . }}
  labels:
    {{- include "platformServiceAccounts.labels.standard" . | nindent 4 }}
    platform.apolo.us/ping: "true"
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    platform.apolo.us/ping-url: http://{{ include "platformServiceAccounts.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.port }}/ping
    {{- if .Capabilities.APIVersions.Has "traefik.io/v1alpha1" }}
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: NEURO_SERVICE_ACCOUNTS_API_SESSION
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: tcp-web
  selector:
    app: {{ include "platformServiceAccounts.name" . }}
    release: {{ .Release.Name }}
    service: platform-service-accounts
