apiVersion: v2
name: platform-service-accounts
description: Neu.ro service accounts service
version: $CHART_VERSION
appVersion: $APP_VERSION
dependencies:
  - name: k8s-resources
    version: "1.0.1"
    repository: https://neuro-inc.github.io/helm-charts
  - name: postgres-db-init
    version: "1.1.0"
    repository: https://neuro-inc.github.io/helm-charts
