ingress:
  enabled: true
  hosts: [dev.neu.ro]

sentry:
  dsn: https://432bc48cd2444be7afec5efeb1fc03a6@o489136.ingest.sentry.io/5530426
  clusterName: dev
  sampleRate: 0.002

platform:
  apiPublicUrl: https://dev.neu.ro/api/v1
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: admin_token

postgres:
  dsn:
    valueFrom:
      secretKeyRef:
        name: platformserviceaccountsapi-postgres
        key: platformserviceaccountsapi-service-dsn

postgres-db-init:
  adminDsn:
    valueFrom:
      secretKeyRef:
        name: postgres
        key: admin-dsn
  migrationsRunnerDsn:
    valueFrom:
      secretKeyRef:
        name: platformserviceaccountsapi-postgres
        key: platformserviceaccountsapi-migrations-dsn
  serviceDsn:
    valueFrom:
      secretKeyRef:
        name: platformserviceaccountsapi-postgres
        key: platformserviceaccountsapi-service-dsn

  migrations:
    env:
      - name: NP_DB_POSTGRES_DSN
        valueFrom:
          secretKeyRef:
            name: platformserviceaccountsapi-postgres
            key: platformserviceaccountsapi-migrations-dsn


cors:
  origins:
  - *

enableDocs: true
