ingress:
  enabled: true
  hosts: [ml.cloud.mts.ru]

platform:
  apiPublicUrl: https://ml.cloud.mts.ru/api/v1
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: admin_token

postgres:
  dsn:
    valueFrom:
      secretKeyRef:
        name: platformserviceaccountsapi-postgres
        key: platformserviceaccountsapi-service-dsn

postgres-db-init:
  adminDsn:
    valueFrom:
      secretKeyRef:
        name: postgres
        key: admin-dsn
  migrationsRunnerDsn:
    valueFrom:
      secretKeyRef:
        name: platformserviceaccountsapi-postgres
        key: platformserviceaccountsapi-migrations-dsn
  serviceDsn:
    valueFrom:
      secretKeyRef:
        name: platformserviceaccountsapi-postgres
        key: platformserviceaccountsapi-service-dsn

  migrations:
    env:
      - name: NP_DB_POSTGRES_DSN
        valueFrom:
          secretKeyRef:
            name: platformserviceaccountsapi-postgres
            key: platformserviceaccountsapi-migrations-dsn

cors:
  origins:
  - https://ml.cloud.mts.ru

enableDocs: true
