name: CI

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]
  schedule:
  - cron: 0 4 * * *

jobs:
  test:
    name: All checks are passed
    uses: ./.github/workflows/test.yaml

  release:
    name: Create release
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
    uses: neuro-inc/reuse/.github/workflows/release-service.yaml@v24.10.0
    with:
      image: platformserviceaccountsapi
      helm_charts: platform-service-accounts

  deploy:
    name: Deploy
    needs: release
    uses: neuro-inc/reuse/.github/workflows/deploy-service.yaml@v24.10.0
    secrets:
      tf_api_token: ${{ secrets.TF_API_TOKEN }}
    with:
      environment: ${{ needs.release.outputs.prerelease == 'true' && 'dev' || 'prod' }}
      dev_workspace: ${{ vars.DEV_TFC_WORKSPACE_JSON }}
      prod_workspaces: ${{ vars.PROD_TFC_WORKSPACES_JSON }}
      variables: |
        platform_service_accounts_version=${{ needs.release.outputs.version }}
