name: CI

on:
  push:
    branches: [master]
    tags: [v*.*, v*.*.*]
  pull_request:
    branches: [master]
  pull_request_target:
    branches: [master]
  schedule:
  - cron: 0 4 * * *

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    if: |
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]')
    env:
      CLOUD_PROVIDER: ${{ secrets.CLOUD_PROVIDER_DEV }}
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.10
    - name: Cache packages
      uses: actions/cache@v2.1.6
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-py-3.8.10-${{ hashFiles('requirements/*.txt') }}-${{
          hashFiles('setup.py') }}
    - name: Install dependencies
      run: make setup
    - name: Lint
      run: |
        echo "::add-matcher::.github/actionlint-matcher.json"
        make lint
    - name: Run unit tests
      run: make test_unit
    - name: Configure AWS credentials
      if: env.CLOUD_PROVIDER == 'aws'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to AWS ECR
      if: env.CLOUD_PROVIDER == 'aws'
      uses: aws-actions/amazon-ecr-login@v1
    - name: Configure Azure credentials
      if: env.CLOUD_PROVIDER == 'azure'
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Login to Azure ACR
      if: env.CLOUD_PROVIDER == 'azure'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_DEV_ACR_SERVER }}
        username: ${{ secrets.AZURE_DEV_ACR_USERNAME }}
        password: ${{ secrets.AZURE_DEV_ACR_PASSWORD }}
    - name: Run integration tests
      run: make test_integration
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: .coverage-integration.xml
        flags: integration
        name: codecov-integration
    - name: Build Docker image
      run: make docker_build
      env:
        TAG: latest
    - name: Upload image artifact
      uses: neuro-inc/upload-image-action@v21.9.2
      with:
        image: platformserviceaccountsapi
        token: ${{ secrets.GITHUB_TOKEN }}
  deploy_dev:
    name: Deploy to dev
    environment: dev
    runs-on: ubuntu-latest
    needs: test
    concurrency: deploy_dev
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AZURE_ACR_NAME: ${{ secrets.AZURE_DEV_ACR_NAME }}
      AZURE_REGION: ${{ secrets.AZURE_DEV_REGION }}
      AZURE_RG_NAME: ${{ secrets.AZURE_DEV_RG_NAME }}
      CLUSTER_NAME: ${{ secrets.DEV_CLUSTER_NAME }}
      HELM_ENV: dev
      CLOUD_PROVIDER: ${{ secrets.CLOUD_PROVIDER_DEV }}
      IMAGE_REGISTRY: ${{ secrets.CLOUD_PROVIDER_DEV }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.7.0
    - name: Configure AWS credentials
      if: env.CLOUD_PROVIDER == 'aws'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to AWS ECR
      if: env.CLOUD_PROVIDER == 'aws'
      uses: aws-actions/amazon-ecr-login@v1
    - name: Configure Azure credentials
      if: env.CLOUD_PROVIDER == 'azure'
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Login to Azure ACR
      if: env.CLOUD_PROVIDER == 'azure'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_DEV_ACR_SERVER }}
        username: ${{ secrets.AZURE_DEV_ACR_USERNAME }}
        password: ${{ secrets.AZURE_DEV_ACR_PASSWORD }}
    - name: Build image
      run: make docker_build
    - name: Push image to registry
      run: |
        make docker_push
        IMAGE_TAG=latest make docker_push
    - name: Update kube config
      run: make ${{ env.CLOUD_PROVIDER }}_k8s_login
    - name: Deploy to kubernetes
      run: make helm_deploy
  deploy_staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AZURE_ACR_NAME: ${{ secrets.AZURE_STAGING_ACR_NAME }}
      AZURE_REGION: ${{ secrets.AZURE_STAGING_REGION }}
      AZURE_RG_NAME: ${{ secrets.AZURE_STAGING_RG_NAME }}
      CLUSTER_NAME: ${{ secrets.STAGING_CLUSTER_NAME }}
      HELM_ENV: staging
      CLOUD_PROVIDER: ${{ secrets.CLOUD_PROVIDER_STAGING }}
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.7.0
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      if: env.CLOUD_PROVIDER == 'aws'
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Configure Azure credentials
      if: env.CLOUD_PROVIDER == 'azure'
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set environment variables
      run: |
        VERSION="${GITHUB_REF#refs/tags/v}"
        {
          echo "IMAGE_TAG=$VERSION"
          echo "HELM_CHART_VERSION=$VERSION"
          echo "HELM_APP_VERSION=$VERSION"
        } >> $GITHUB_ENV
    - name: Build image
      run: make docker_build
    - name: Push image to registry
      run: make docker_push
    - name: Update kube config
      run: make ${{ env.CLOUD_PROVIDER }}_k8s_login
    - name: Deploy to kubernetes
      run: make artifactory_helm_deploy
